cd /d %~dp0/test
rm -fr ../test_out
cp -fr ../Debug-x64/vc143/yggr_lua_base_type.dll ./
"../Debug-x64/vc143/nsql_database_system_base_bson_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_bson_serialize_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_basic_demo.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_basic_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_binary_buffer_ref_operator_set_test_equal.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_binary_buffer_ref_operator_set_test_liner_only.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_binary_buffer_ref_operator_set_test_sizeof_greater.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_binary_buffer_ref_operator_set_test_sizeof_less.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_binary_buffer_ref_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_binary_buffer_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_code_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_code_w_scope_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_date_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_date_time_timeval_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_dbpointer_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_decimal128_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_error_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_oid_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_oid_test2.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_regex_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_symbol_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_time_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_timestamp_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_timeval_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_value_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_bson_value_test2.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_apm_callbacks_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_auto_encryption_opts_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_client_encryption_datakey_opts_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_client_encryption_encrypt_opts_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_client_encryption_encrypt_range_opts_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_client_encryption_opts_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_client_encryption_rewrap_many_datakey_result_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_connection_init_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_find_and_modify_opts_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_gridfs_file_opt_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_gridfs_file_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_host_info_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_index_model_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_read_concern_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_read_prefs_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_server_api_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_ssl_opt_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_stream_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_uri_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_c_mongo_write_concern_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_cert_file_win32_load_failed_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_mongo_accesser_encryption_test_of_connect.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_mongo_accesser_encryption_test_of_connect_pool.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_mongo_accesser_test_of_connection.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_mongo_accesser_test_of_connection_mt.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_mongo_accesser_test_of_connection_pool.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_mongo_accesser_test_of_connection_pool_mt.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_mongo_accesser_test_of_connection_sharding.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_mongo_gridfs_bucket_org_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_mongo_gridfs_org_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_mongo_operators_dollar_cmd_def_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_mongoc_connection_pool_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_mongodbc_basic_connect_test.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_test_mongodb_async_mgr.exe" --batch-test
"../Debug-x64/vc143/nsql_database_system_test_mongodb_mgr.exe" --batch-test
echo '---------all test end-----------------'
cd ..